'''3. Write a Python program to compute the sum of the even-valued terms in the Fibonacci sequence whose values do not exceed one million
Note: Fibonacci series is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...'''

cache = {}
def fiba(n):
     cache[n] = cache.get(n, 0) or (n <= 1 and 1 or fiba(n-1) + fiba(n-2))
     return cache[n]
n = 0
x = 0
while fiba(x) <= 1000000:
       if not fiba(x) % 2: n = n + fiba(x)
       x=x+1
print(n)
